// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




type NodeFunctionality struct {
}

// AssertNodeFunctionalityRequired checks if the required fields are not zero-ed
func AssertNodeFunctionalityRequired(obj NodeFunctionality) error {
	return nil
}

// AssertNodeFunctionalityConstraints checks if the values respects the defined constraints
func AssertNodeFunctionalityConstraints(obj NodeFunctionality) error {
	return nil
}
