// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




type PduAddress struct {

	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. 
	PduIPv4Address string `json:"pduIPv4Address,omitempty"`

	PduIPv6AddresswithPrefix Ipv6Addr `json:"pduIPv6AddresswithPrefix,omitempty"`

	PduAddressprefixlength int32 `json:"pduAddressprefixlength,omitempty"`

	IPv4dynamicAddressFlag bool `json:"iPv4dynamicAddressFlag,omitempty"`

	IPv6dynamicPrefixFlag bool `json:"iPv6dynamicPrefixFlag,omitempty"`
}

// AssertPduAddressRequired checks if the required fields are not zero-ed
func AssertPduAddressRequired(obj PduAddress) error {
	if err := AssertIpv6AddrRequired(obj.PduIPv6AddresswithPrefix); err != nil {
		return err
	}
	return nil
}

// AssertPduAddressConstraints checks if the values respects the defined constraints
func AssertPduAddressConstraints(obj PduAddress) error {
	return nil
}
