// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




// UserLocation - At least one of eutraLocation, nrLocation and n3gaLocation shall be present. Several of them may be present. 
type UserLocation struct {

	EutraLocation EutraLocation `json:"eutraLocation,omitempty"`

	NrLocation NrLocation `json:"nrLocation,omitempty"`

	N3gaLocation N3gaLocation `json:"n3gaLocation,omitempty"`

	UtraLocation UtraLocation `json:"utraLocation,omitempty"`

	GeraLocation GeraLocation `json:"geraLocation,omitempty"`
}

// AssertUserLocationRequired checks if the required fields are not zero-ed
func AssertUserLocationRequired(obj UserLocation) error {
	if err := AssertEutraLocationRequired(obj.EutraLocation); err != nil {
		return err
	}
	if err := AssertNrLocationRequired(obj.NrLocation); err != nil {
		return err
	}
	if err := AssertN3gaLocationRequired(obj.N3gaLocation); err != nil {
		return err
	}
	if err := AssertUtraLocationRequired(obj.UtraLocation); err != nil {
		return err
	}
	if err := AssertGeraLocationRequired(obj.GeraLocation); err != nil {
		return err
	}
	return nil
}

// AssertUserLocationConstraints checks if the values respects the defined constraints
func AssertUserLocationConstraints(obj UserLocation) error {
	return nil
}
