// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




type ServingNetworkFunctionId struct {

	ServingNetworkFunctionInformation NfIdentification `json:"servingNetworkFunctionInformation"`

	// String identifying the AMF ID composed of AMF Region ID (8 bits), AMF Set ID (10 bits) and AMF  Pointer (6 bits) as specified in clause 2.10.1 of 3GPP TS 23.003. It is encoded as a string of  6 hexadecimal characters (i.e., 24 bits).  
	AMFId string `json:"aMFId,omitempty"`
}

// AssertServingNetworkFunctionIdRequired checks if the required fields are not zero-ed
func AssertServingNetworkFunctionIdRequired(obj ServingNetworkFunctionId) error {
	elements := map[string]interface{}{
		"servingNetworkFunctionInformation": obj.ServingNetworkFunctionInformation,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNfIdentificationRequired(obj.ServingNetworkFunctionInformation); err != nil {
		return err
	}
	return nil
}

// AssertServingNetworkFunctionIdConstraints checks if the values respects the defined constraints
func AssertServingNetworkFunctionIdConstraints(obj ServingNetworkFunctionId) error {
	return nil
}
