// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




// QueryParamCombination - Contains a list of Query Parameters
type QueryParamCombination struct {

	QueryParams []QueryParameter `json:"queryParams"`
}

// AssertQueryParamCombinationRequired checks if the required fields are not zero-ed
func AssertQueryParamCombinationRequired(obj QueryParamCombination) error {
	elements := map[string]interface{}{
		"queryParams": obj.QueryParams,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.QueryParams {
		if err := AssertQueryParameterRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertQueryParamCombinationConstraints checks if the values respects the defined constraints
func AssertQueryParamCombinationConstraints(obj QueryParamCombination) error {
	return nil
}
