// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




// TransportProtocol - Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol.  
type TransportProtocol struct {
}

// AssertTransportProtocolRequired checks if the required fields are not zero-ed
func AssertTransportProtocolRequired(obj TransportProtocol) error {
	return nil
}

// AssertTransportProtocolConstraints checks if the values respects the defined constraints
func AssertTransportProtocolConstraints(obj TransportProtocol) error {
	return nil
}
