// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




type RanSecondaryRatUsageReport struct {

	RANSecondaryRATType RatType `json:"rANSecondaryRATType,omitempty"`

	QosFlowsUsageReports []QosFlowsUsageReport `json:"qosFlowsUsageReports,omitempty"`
}

// AssertRanSecondaryRatUsageReportRequired checks if the required fields are not zero-ed
func AssertRanSecondaryRatUsageReportRequired(obj RanSecondaryRatUsageReport) error {
	if err := AssertRatTypeRequired(obj.RANSecondaryRATType); err != nil {
		return err
	}
	for _, el := range obj.QosFlowsUsageReports {
		if err := AssertQosFlowsUsageReportRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRanSecondaryRatUsageReportConstraints checks if the values respects the defined constraints
func AssertRanSecondaryRatUsageReportConstraints(obj RanSecondaryRatUsageReport) error {
	return nil
}
