// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 */

package openapi




type NetworkSlicingInfo struct {

	SNSSAI Snssai `json:"sNSSAI"`
}

// AssertNetworkSlicingInfoRequired checks if the required fields are not zero-ed
func AssertNetworkSlicingInfoRequired(obj NetworkSlicingInfo) error {
	elements := map[string]interface{}{
		"sNSSAI": obj.SNSSAI,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertSnssaiRequired(obj.SNSSAI); err != nil {
		return err
	}
	return nil
}

// AssertNetworkSlicingInfoConstraints checks if the values respects the defined constraints
func AssertNetworkSlicingInfoConstraints(obj NetworkSlicingInfo) error {
	return nil
}
