/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccessType.h
 *
 * Indicates whether the access is  via 3GPP or via non-3GPP.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AccessType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AccessType_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  AccessType
    : public ModelBase
{
public:
    AccessType();
    virtual ~AccessType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAccessType
    {
        AccessType__3GPP_ACCESS,
        AccessType_NON_3GPP_ACCESS,
    };

    eAccessType getValue() const;
    void setValue(eAccessType const value);

    protected:
        eAccessType m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AccessType_H_ */
