/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AccessTypeRm.h
 *
 * Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI  &#39;nullable: true&#39; property.\&quot; 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AccessTypeRm_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AccessTypeRm_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/AccessType.h"
#include "CppRestOpenAPIClient/model/NullValue.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI  &#39;nullable: true&#39; property.\&quot; 
/// </summary>
class  AccessTypeRm
    : public ModelBase
{
public:
    AccessTypeRm();
    virtual ~AccessTypeRm();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AccessTypeRm members


protected:
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AccessTypeRm_H_ */
