/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * NetworkSlicingInfo.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_NetworkSlicingInfo_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_NetworkSlicingInfo_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Snssai.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Snssai;

/// <summary>
/// 
/// </summary>
class  NetworkSlicingInfo
    : public ModelBase
{
public:
    NetworkSlicingInfo();
    virtual ~NetworkSlicingInfo();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NetworkSlicingInfo members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Snssai> getSNSSAI() const;
    bool sNSSAIIsSet() const;
    void unsetSNSSAI();

    void setSNSSAI(const std::shared_ptr<Snssai>& value);


protected:
    std::shared_ptr<Snssai> m_SNSSAI;
    bool m_SNSSAIIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_NetworkSlicingInfo_H_ */
