/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * NgApCause.h
 *
 * Represents the NGAP cause.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_NgApCause_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_NgApCause_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Represents the NGAP cause.
/// </summary>
class  NgApCause
    : public ModelBase
{
public:
    NgApCause();
    virtual ~NgApCause();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NgApCause members

    /// <summary>
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    /// </summary>
    int32_t getGroup() const;
    bool groupIsSet() const;
    void unsetGroup();

    void setGroup(int32_t value);

    /// <summary>
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    /// </summary>
    int32_t getValue() const;
    bool valueIsSet() const;
    void unsetValue();

    void setValue(int32_t value);


protected:
    int32_t m_Group;
    bool m_GroupIsSet;
    int32_t m_Value;
    bool m_ValueIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_NgApCause_H_ */
