/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PduSetQosPara.h
 *
 * Represents the PDU Set level QoS parameters.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_PduSetQosPara_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_PduSetQosPara_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/PduSetHandlingInfo.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Represents the PDU Set level QoS parameters.
/// </summary>
class  PduSetQosPara
    : public ModelBase
{
public:
    PduSetQosPara();
    virtual ~PduSetQosPara();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PduSetQosPara members

    /// <summary>
    /// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501 [8])), expressed in 0.01 milliseconds. 
    /// </summary>
    int32_t getPduSetDelayBudget() const;
    bool pduSetDelayBudgetIsSet() const;
    void unsetPduSetDelayBudget();

    void setPduSetDelayBudget(int32_t value);

    /// <summary>
    /// String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \&quot;scalar x 10-k\&quot; where the scalar and the exponent k are each encoded as one decimal digit. 
    /// </summary>
    utility::string_t getPduSetErrRate() const;
    bool pduSetErrRateIsSet() const;
    void unsetPduSetErrRate();

    void setPduSetErrRate(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PduSetHandlingInfo> getPduSetHandlingInfo() const;
    bool pduSetHandlingInfoIsSet() const;
    void unsetPduSetHandlingInfo();

    void setPduSetHandlingInfo(const std::shared_ptr<PduSetHandlingInfo>& value);


protected:
    int32_t m_PduSetDelayBudget;
    bool m_PduSetDelayBudgetIsSet;
    utility::string_t m_PduSetErrRate;
    bool m_PduSetErrRateIsSet;
    std::shared_ptr<PduSetHandlingInfo> m_PduSetHandlingInfo;
    bool m_PduSetHandlingInfoIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_PduSetQosPara_H_ */
