/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QosData.h
 *
 * Contains the QoS parameters.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_QosData_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_QosData_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/Arp.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/PduSetQosParaRm.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Arp;
class PduSetQosParaRm;

/// <summary>
/// Contains the QoS parameters.
/// </summary>
class  QosData
    : public ModelBase
{
public:
    QosData();
    virtual ~QosData();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// QosData members

    /// <summary>
    /// Univocally identifies the QoS control policy data within a PDU session.
    /// </summary>
    utility::string_t getQosId() const;
    bool qosIdIsSet() const;
    void unsetQosId();

    void setQosId(const utility::string_t& value);

    /// <summary>
    /// Unsigned integer representing a 5G QoS Identifier (see clause 5.7.2.1 of 3GPP TS 23.501, within the range 0 to 255. 
    /// </summary>
    int32_t getR5qi() const;
    bool r5qiIsSet() const;
    void unsetr_5qi();

    void setR5qi(int32_t value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;BitRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    utility::string_t getMaxbrUl() const;
    bool maxbrUlIsSet() const;
    void unsetMaxbrUl();

    void setMaxbrUl(const utility::string_t& value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;BitRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    utility::string_t getMaxbrDl() const;
    bool maxbrDlIsSet() const;
    void unsetMaxbrDl();

    void setMaxbrDl(const utility::string_t& value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;BitRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    utility::string_t getGbrUl() const;
    bool gbrUlIsSet() const;
    void unsetGbrUl();

    void setGbrUl(const utility::string_t& value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;BitRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    utility::string_t getGbrDl() const;
    bool gbrDlIsSet() const;
    void unsetGbrDl();

    void setGbrDl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Arp> getArp() const;
    bool arpIsSet() const;
    void unsetArp();

    void setArp(const std::shared_ptr<Arp>& value);

    /// <summary>
    /// Indicates whether notifications are requested from 3GPP NG-RAN when the GFBR can no longer (or again) be guaranteed for a QoS Flow during the lifetime of the QoS Flow. 
    /// </summary>
    bool isQnc() const;
    bool qncIsSet() const;
    void unsetQnc();

    void setQnc(bool value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;5QiPriorityLevel&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getPriorityLevel() const;
    bool priorityLevelIsSet() const;
    void unsetPriorityLevel();

    void setPriorityLevel(int32_t value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;AverWindow&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getAverWindow() const;
    bool averWindowIsSet() const;
    void unsetAverWindow();

    void setAverWindow(int32_t value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;MaxDataBurstVol&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getMaxDataBurstVol() const;
    bool maxDataBurstVolIsSet() const;
    void unsetMaxDataBurstVol();

    void setMaxDataBurstVol(int32_t value);

    /// <summary>
    /// Indicates whether the QoS information is reflective for the corresponding service data  flow. 
    /// </summary>
    bool isReflectiveQos() const;
    bool reflectiveQosIsSet() const;
    void unsetReflectiveQos();

    void setReflectiveQos(bool value);

    /// <summary>
    /// Indicates, by containing the same value, what PCC rules may share resource in downlink  direction. 
    /// </summary>
    utility::string_t getSharingKeyDl() const;
    bool sharingKeyDlIsSet() const;
    void unsetSharingKeyDl();

    void setSharingKeyDl(const utility::string_t& value);

    /// <summary>
    /// Indicates, by containing the same value, what PCC rules may share resource in uplink  direction. 
    /// </summary>
    utility::string_t getSharingKeyUl() const;
    bool sharingKeyUlIsSet() const;
    void unsetSharingKeyUl();

    void setSharingKeyUl(const utility::string_t& value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;PacketLossRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getMaxPacketLossRateDl() const;
    bool maxPacketLossRateDlIsSet() const;
    void unsetMaxPacketLossRateDl();

    void setMaxPacketLossRateDl(int32_t value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;PacketLossRate&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getMaxPacketLossRateUl() const;
    bool maxPacketLossRateUlIsSet() const;
    void unsetMaxPacketLossRateUl();

    void setMaxPacketLossRateUl(int32_t value);

    /// <summary>
    /// Indicates that the dynamic PCC rule shall always have its binding with the QoS Flow  associated with the default QoS rule 
    /// </summary>
    bool isDefQosFlowIndication() const;
    bool defQosFlowIndicationIsSet() const;
    void unsetDefQosFlowIndication();

    void setDefQosFlowIndication(bool value);

    /// <summary>
    /// This data type is defined in the same way as the &#39;ExtMaxDataBurstVol&#39; data type, but with the OpenAPI &#39;nullable: true&#39; property. 
    /// </summary>
    int32_t getExtMaxDataBurstVol() const;
    bool extMaxDataBurstVolIsSet() const;
    void unsetExtMaxDataBurstVol();

    void setExtMaxDataBurstVol(int32_t value);

    /// <summary>
    /// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. 
    /// </summary>
    int32_t getPacketDelayBudget() const;
    bool packetDelayBudgetIsSet() const;
    void unsetPacketDelayBudget();

    void setPacketDelayBudget(int32_t value);

    /// <summary>
    /// String representing Packet Error Rate (see clause 5.7.3.5 and 5.7.4 of 3GPP TS 23.501, expressed as a \&quot;scalar x 10-k\&quot; where the scalar and the exponent k are each encoded as one decimal digit. 
    /// </summary>
    utility::string_t getPacketErrorRate() const;
    bool packetErrorRateIsSet() const;
    void unsetPacketErrorRate();

    void setPacketErrorRate(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PduSetQosParaRm> getPduSetQosDl() const;
    bool pduSetQosDlIsSet() const;
    void unsetPduSetQosDl();

    void setPduSetQosDl(const std::shared_ptr<PduSetQosParaRm>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PduSetQosParaRm> getPduSetQosUl() const;
    bool pduSetQosUlIsSet() const;
    void unsetPduSetQosUl();

    void setPduSetQosUl(const std::shared_ptr<PduSetQosParaRm>& value);


protected:
    utility::string_t m_QosId;
    bool m_QosIdIsSet;
    int32_t m_r_5qi;
    bool m_r_5qiIsSet;
    utility::string_t m_MaxbrUl;
    bool m_MaxbrUlIsSet;
    utility::string_t m_MaxbrDl;
    bool m_MaxbrDlIsSet;
    utility::string_t m_GbrUl;
    bool m_GbrUlIsSet;
    utility::string_t m_GbrDl;
    bool m_GbrDlIsSet;
    std::shared_ptr<Arp> m_Arp;
    bool m_ArpIsSet;
    bool m_Qnc;
    bool m_QncIsSet;
    int32_t m_PriorityLevel;
    bool m_PriorityLevelIsSet;
    int32_t m_AverWindow;
    bool m_AverWindowIsSet;
    int32_t m_MaxDataBurstVol;
    bool m_MaxDataBurstVolIsSet;
    bool m_ReflectiveQos;
    bool m_ReflectiveQosIsSet;
    utility::string_t m_SharingKeyDl;
    bool m_SharingKeyDlIsSet;
    utility::string_t m_SharingKeyUl;
    bool m_SharingKeyUlIsSet;
    int32_t m_MaxPacketLossRateDl;
    bool m_MaxPacketLossRateDlIsSet;
    int32_t m_MaxPacketLossRateUl;
    bool m_MaxPacketLossRateUlIsSet;
    bool m_DefQosFlowIndication;
    bool m_DefQosFlowIndicationIsSet;
    int32_t m_ExtMaxDataBurstVol;
    bool m_ExtMaxDataBurstVolIsSet;
    int32_t m_PacketDelayBudget;
    bool m_PacketDelayBudgetIsSet;
    utility::string_t m_PacketErrorRate;
    bool m_PacketErrorRateIsSet;
    std::shared_ptr<PduSetQosParaRm> m_PduSetQosDl;
    bool m_PduSetQosDlIsSet;
    std::shared_ptr<PduSetQosParaRm> m_PduSetQosUl;
    bool m_PduSetQosUlIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_QosData_H_ */
