/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QueryParamCombination.h
 *
 * Contains a list of Query Parameters
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_QueryParamCombination_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_QueryParamCombination_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/QueryParameter.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class QueryParameter;

/// <summary>
/// Contains a list of Query Parameters
/// </summary>
class  QueryParamCombination
    : public ModelBase
{
public:
    QueryParamCombination();
    virtual ~QueryParamCombination();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// QueryParamCombination members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<QueryParameter>>& getQueryParams();
    bool queryParamsIsSet() const;
    void unsetQueryParams();

    void setQueryParams(const std::vector<std::shared_ptr<QueryParameter>>& value);


protected:
    std::vector<std::shared_ptr<QueryParameter>> m_QueryParams;
    bool m_QueryParamsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_QueryParamCombination_H_ */
