/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SteerModeIndicator.h
 *
 * Contains Autonomous load-balance indicator or UE-assistance indicator.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SteerModeIndicator_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SteerModeIndicator_H_


#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Contains Autonomous load-balance indicator or UE-assistance indicator.
/// </summary>
class  SteerModeIndicator
    : public ModelBase
{
public:
    SteerModeIndicator();
    virtual ~SteerModeIndicator();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SteerModeIndicator members


protected:
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SteerModeIndicator_H_ */
