/**
* Nchf_OfflineOnlyCharging
* OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "ChargingDataRequest.h"
#include "ChargingDataResponse.h"
#include "ProblemDetails.h"
#include <string>

namespace org::openapitools::server::api
{

class  DefaultApi : public ApiBase {
public:
    explicit DefaultApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~DefaultApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void offlinechargingdata_offline_charging_data_ref_release_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void offlinechargingdata_offline_charging_data_ref_update_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void offlinechargingdata_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void default_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="offlineChargingDataRef">a unique identifier for a charging data resource in a PLMN</param>
    /// <param name="chargingDataRequest"></param>
    virtual void offlinechargingdata_offline_charging_data_ref_release_post(const std::string &offlineChargingDataRef, const org::openapitools::server::model::ChargingDataRequest &chargingDataRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="offlineChargingDataRef">a unique identifier for a charging data resource in a PLMN</param>
    /// <param name="chargingDataRequest"></param>
    virtual void offlinechargingdata_offline_charging_data_ref_update_post(const std::string &offlineChargingDataRef, const org::openapitools::server::model::ChargingDataRequest &chargingDataRequest, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="chargingDataRequest"></param>
    virtual void offlinechargingdata_post(const org::openapitools::server::model::ChargingDataRequest &chargingDataRequest, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* DefaultApi_H_ */

