/**
* Nchf_OfflineOnlyCharging
* OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * r_3GPPPSDataOffStatus.h
 *
 * 
 */

#ifndef r_3GPPPSDataOffStatus_H_
#define r_3GPPPSDataOffStatus_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  r_3GPPPSDataOffStatus
{
public:
    r_3GPPPSDataOffStatus();
    virtual ~r_3GPPPSDataOffStatus() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const r_3GPPPSDataOffStatus& rhs) const;
    bool operator!=(const r_3GPPPSDataOffStatus& rhs) const;

    /////////////////////////////////////////////
    /// r_3GPPPSDataOffStatus members


    friend  void to_json(nlohmann::json& j, const r_3GPPPSDataOffStatus& o);
    friend  void from_json(const nlohmann::json& j, r_3GPPPSDataOffStatus& o);
protected:
    
};

} // namespace org::openapitools::server::model

#endif /* r_3GPPPSDataOffStatus_H_ */
