/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AccessType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

AccessType::eAccessType toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("3GPP_ACCESS")))
        return AccessType::eAccessType::AccessType__3GPP_ACCESS;
    if (val == utility::conversions::to_string_t(U("NON_3GPP_ACCESS")))
        return AccessType::eAccessType::AccessType_NON_3GPP_ACCESS;
    return {};
}

EnumUnderlyingType fromEnum(AccessType::eAccessType e)
{
    switch (e)
    {
    case AccessType::eAccessType::AccessType__3GPP_ACCESS:
        return U("3GPP_ACCESS");
    case AccessType::eAccessType::AccessType_NON_3GPP_ACCESS:
        return U("NON_3GPP_ACCESS");
    default:
        break;
    }
    return {};
}
}

AccessType::AccessType()
{
}

AccessType::~AccessType()
{
}

void AccessType::validate()
{
    // TODO: implement validation
}

web::json::value AccessType::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool AccessType::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void AccessType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool AccessType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

AccessType::eAccessType AccessType::getValue() const
{
   return m_value;
}

void AccessType::setValue(AccessType::eAccessType const value)
{
   m_value = value;
}


}
}
}
}


