/**
 * Nchf_OfflineOnlyCharging
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0-alpha.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/GNbId.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



GNbId::GNbId()
{
    m_BitLength = 0;
    m_BitLengthIsSet = false;
    m_GNBValue = utility::conversions::to_string_t("");
    m_GNBValueIsSet = false;
}

GNbId::~GNbId()
{
}

void GNbId::validate()
{
    // TODO: implement validation
}

web::json::value GNbId::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_BitLengthIsSet)
    {
        val[utility::conversions::to_string_t(U("bitLength"))] = ModelBase::toJson(m_BitLength);
    }
    if(m_GNBValueIsSet)
    {
        val[utility::conversions::to_string_t(U("gNBValue"))] = ModelBase::toJson(m_GNBValue);
    }

    return val;
}

bool GNbId::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("bitLength"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("bitLength")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setBitLength;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBitLength);
            setBitLength(refVal_setBitLength);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("gNBValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("gNBValue")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGNBValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGNBValue);
            setGNBValue(refVal_setGNBValue);
        }
    }
    return ok;
}

void GNbId::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_BitLengthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("bitLength")), m_BitLength));
    }
    if(m_GNBValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("gNBValue")), m_GNBValue));
    }
}

bool GNbId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("bitLength"))))
    {
        int32_t refVal_setBitLength;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("bitLength"))), refVal_setBitLength );
        setBitLength(refVal_setBitLength);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("gNBValue"))))
    {
        utility::string_t refVal_setGNBValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("gNBValue"))), refVal_setGNBValue );
        setGNBValue(refVal_setGNBValue);
    }
    return ok;
}

int32_t GNbId::getBitLength() const
{
    return m_BitLength;
}

void GNbId::setBitLength(int32_t value)
{
    m_BitLength = value;
    m_BitLengthIsSet = true;
}

bool GNbId::bitLengthIsSet() const
{
    return m_BitLengthIsSet;
}

void GNbId::unsetBitLength()
{
    m_BitLengthIsSet = false;
}
utility::string_t GNbId::getGNBValue() const
{
    return m_GNBValue;
}

void GNbId::setGNBValue(const utility::string_t& value)
{
    m_GNBValue = value;
    m_GNBValueIsSet = true;
}

bool GNbId::gNBValueIsSet() const
{
    return m_GNBValueIsSet;
}

void GNbId::unsetGNBValue()
{
    m_GNBValueIsSet = false;
}
}
}
}
}


